name: cmake build

on: [push]

jobs:
  build:
    name: '${{ matrix.os }}: build'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Why not true?
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    # Setup the build machine with the most recent versions of CMake and Ninja.
    # Both are cached if not already: on subsequent runs both will be quickly
    # restored from GitHub cache service.
    - uses: lukka/get-cmake@latest

    # This step will only be required for ubuntu
    - name: Install libudev on ubuntu
      run: sudo apt-get install -y libudev-dev
      if: matrix.os == 'ubuntu-latest'

    - name: run-cmake
      uses: lukka/run-cmake@v10.1
      with:
          # This is the default path to the CMakeLists.txt along side the
          # CMakePresets.json. Change if you need have CMakeLists.txt and CMakePresets.json
          # located elsewhere.
          # cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'

          # This is the name of the CMakePresets.json's configuration to use to generate
          # the project files. This configuration leverages the vcpkg.cmake toolchain file to
          # run vcpkg and install all dependencies specified in vcpkg.json.
          configurePreset: 'ninja'

          # This is the name of the CMakePresets.json's configuration to build the project.
          buildPreset: 'ninja'

    - name: upload executable
      uses: actions/upload-artifact@v3
      with:
        name: trampoline-${{ matrix.os }}
        path: ${{ github.workspace}}/build/trampoline*

  # release:
  #   needs: [build]
  #   steps:
      
  


    # TODO: both macos and ubuntu executables are called "trampoline":  we have
    # to distinguish them in the release.


    # TODO: these steps need to run in a separate job that is executed on tags
    # only and depends on build.

    # - name: Compute release version
    #   run: |
    #     echo ${{ github.sha }} > RELEASE.txt

    # - name: Package release
    #   run: |
    #     tar cz trampoline-* RELEASE.txt README.md LICENSE >release.${{ github.sha }}.tgz

    # - name: GH Release
    #   uses: softprops/action-gh-release@v0.1.15
    #   if: startsWith(github.ref, 'refs/tags/')
    #   with:
    #       files: |
    #         release.${{ github.sha }}.tgz

